version: "3"

services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - ./src:/app/src  
    ports:
      - 3000:3000
    environment:     
      - SKIP_PREFLIGHT_CHECK=true